package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Thursday, November 14, 2019 8:46:44 PM PKT
*/

public interface HelloOperations 
{
  String sayHello (int x1, int x2, int x3, int y1, int y2, int y3);
  void shutdown ();
} // interface HelloOperations
